version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# On indique explicitement à Read the Docs d'utiliser MkDocs
mkdocs:
  configuration: mkdocs.yml

# On lui dit d'installer le thème Material avant de compiler
python:
  install:
    - requirements: requirements.txt
