site_name: Plateforme de Télédétection - ANRAC
site_url: https://projet-anrac.readthedocs.io/
theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-night
        name: Mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight

nav:
  - Accueil: index.md
  - Guide d'Installation: guide.md
  - Fonctionnalités UI: UI_features.md
  - Architecture Technique: technical_reference.md
