site_name: Plateforme de Télédétection - ANRAC
theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-night
        name: Passer au mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Accueil: index.md
  - Guide d'Installation: guide.md
  - Fonctionnalités UI: UI_features.md
  - Architecture Technique: technical_reference.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
